services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: superline-admin
    ports:
      - "3001:8080"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: superline-client
    ports:
      - "3002:8080"
    restart: unless-stopped

  agency:
    build:
      context: .
      dockerfile: apps/agency/Dockerfile
    container_name: superline-agency
    ports:
      - "3003:8080"
    restart: unless-stopped
